// +build !ignore_autogenerated

// Code generated by operator-sdk-v0.18.2. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveHealthConfig) DeepCopyInto(out *HiveHealthConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveHealthConfig.
func (in *HiveHealthConfig) DeepCopy() *HiveHealthConfig {
	if in == nil {
		return nil
	}
	out := new(HiveHealthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HiveHealthConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveHealthConfigList) DeepCopyInto(out *HiveHealthConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HiveHealthConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveHealthConfigList.
func (in *HiveHealthConfigList) DeepCopy() *HiveHealthConfigList {
	if in == nil {
		return nil
	}
	out := new(HiveHealthConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HiveHealthConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveHealthConfigSpec) DeepCopyInto(out *HiveHealthConfigSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveHealthConfigSpec.
func (in *HiveHealthConfigSpec) DeepCopy() *HiveHealthConfigSpec {
	if in == nil {
		return nil
	}
	out := new(HiveHealthConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveHealthConfigStatus) DeepCopyInto(out *HiveHealthConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveHealthConfigStatus.
func (in *HiveHealthConfigStatus) DeepCopy() *HiveHealthConfigStatus {
	if in == nil {
		return nil
	}
	out := new(HiveHealthConfigStatus)
	in.DeepCopyInto(out)
	return out
}
